name: "jusdepixel/frontend"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cp /home/jusdepixel-frontend/.env .env
      - run: cp /home/jusdepixel-frontend/sitemap.txt ./sitemap.txt
      - run: cp /home/jusdepixel-frontend/sitemap.txt ./public/sitemap.txt
      - run: npm install --force
      - run: npm run build --if-present
      - run: pm2 reload jusdepixel-frontend
        env:
          CI: true
